stops = [
    'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you',
    'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his',
    'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself',
    'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which',
    'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are',
    'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having',
    'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if',
    'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for',
    'with', 'about', 'against', 'between', 'into', 'through', 'during',
    'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in',
    'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then',
    'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any',
    'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no',
    'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's',
    't', 'can', 'will', 'just', 'don', 'should', 'now', 'id', 'var',
    'function', 'js', 'd', 'script', '\'script', 'fjs', 'document', 'r',
    'b', 'g', 'e', '\'s', 'c', 'f', 'h', 'l', 'k'
    'Array','Date','eval','function',
'hasOwnProperty','Infinity','isFinite','isNaN',
'isPrototypeOf','length','Math','NaN',
'name','Number','Object','prototype',
'String','toString','undefined','valueOf',
'alert','all','anchor','anchors',
'area','assign','blur','button',
'checkbox','clearInterval','clearTimeout','clientInformation',
'close','closed','confirm','constructor',
'crypto','decodeURI','decodeURIComponent','defaultStatus',
'document','element','elements','embed',
'embeds','encodeURI','encodeURIComponent','escape',
'event','fileUpload','focus','form',
'forms','frame','innerHeight','innerWidth',
'layer','layers','link','location',
'mimeTypes','navigate','navigator','frames',
'frameRate','hidden','history','image',
'images','offscreenBuffering','open','opener',
'option','outerHeight','outerWidth','packages',
'pageXOffset','pageYOffset','parent','parseFloat',
'parseInt','password','pkcs11','plugin',
'prompt','propertyIsEnum','radio','reset',
'screenX','screenY','scroll','secure',
'select','self','setInterval','setTimeout',
'status','submit','taint','text',
'textarea','top','unescape','untaint',
'window',
'onblur','onclick','onerror','onfocus',
'onkeydown','onkeypress','onkeyup','onmouseover',
'onload','onmouseup','onmousedown','onsubmit'
]
